### ISSUE TITLE
Cool repo!

### ISSUE THREAD

**Issue by IchikawaYukko** [KeinNerd-net/docker-callofdutyclassic#2]
You are so cool to made this repository!

(This issue is just my impression. So no problem to close.)

**Comment by emeth-** [comment]
Ditto - stumbled across this, COD Classic was the greatest. Super happy you included total war mod as well, I struggled to find a working version of that mod the last few times I tried to spin up a server.

Kudos to you, keep up the good work.

**Comment by KeinNerd** [comment]
Thanks a lot guys!

For me docker is still new. So if you have any suggestions for improvement always bring it to me!
